(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css(){if(document.getElementById('neria-achievement-widget-style'))return;const s=document.createElement('style');s.id='neria-achievement-widget-style';s.textContent='.achievement-profile-link{display:block;width:100%;margin-top:12px;padding:14px;border:1px solid #cdbce8;border-radius:9px;background:linear-gradient(135deg,#f7f3fc,#fff);color:#6d3fc0;text-align:center;text-decoration:none;font-size:14px;font-weight:800}.achievement-profile-link:hover{background:#f1eafd}.profile-achievements-widget{margin-top:18px;padding:18px;background:#fff;border:1px solid #ded7f0;border-radius:13px}.profile-achievements-widget h2{font-size:18px;margin:0 0 5px}.profile-achievements-widget .summary{font-size:12px;color:#777780;margin-bottom:12px}.profile-achievements-list{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.profile-achievement{padding:11px;border:1px solid #e5e5e8;border-radius:10px;background:linear-gradient(145deg,#fff,#faf8fe);min-width:0}.profile-achievement.special{border-color:#e5ce91;background:linear-gradient(145deg,#fff9e9,#fff)}.profile-achievement .ico{font-size:22px}.profile-achievement strong{display:block;font-size:12px;margin-top:5px;overflow-wrap:anywhere}.profile-achievement small{display:block;color:#85858e;font-size:10px;margin-top:4px}.profile-achievements-widget>a{display:inline-block;margin-top:12px;color:#6d3fc0;text-decoration:none;font-size:12px;font-weight:700}@media(max-width:650px){.profile-achievements-list{grid-template-columns:1fr}}';document.head.appendChild(s)}
async function getClient(){return window.supabaseClient||window.sb||null}
async function enhanceOwn(){const card=document.getElementById('profileCard');if(!card||card.dataset.achievementWidget)return;const idEl=card.querySelector('.citizen-id');if(!idEl)return;card.dataset.achievementWidget='1';const a=document.createElement('a');a.className='achievement-profile-link';a.href='achievements.html';a.innerHTML='🏆 Ачивки · <span>загрузка…</span>';idEl.appendChild(a);const client=await getClient();if(!client)return;const {data,error}=await client.rpc('achievement_dashboard');if(error)return;a.querySelector('span').textContent=Number(data.earned_count||0)+' / '+Number(data.total_count||0)}
async function enhancePublic(){const content=document.getElementById('content');if(!content||content.dataset.achievementWidget)return;const id=new URLSearchParams(location.search).get('id');if(!id||!/^\d{1,18}$/.test(id))return;const card=content.querySelector('.card');if(!card)return;content.dataset.achievementWidget='1';const client=await getClient();if(!client)return;const {data,error}=await client.rpc('public_achievement_profile',{p_citizen_number:Number(id)});if(error||!data)return;const box=document.createElement('section');box.className='profile-achievements-widget';const featured=data.featured||[];box.innerHTML='<h2>🏆 Достижения</h2><div class="summary">'+Number(data.earned_count||0)+' / '+Number(data.total_count||0)+' обычных ачивок · '+Number((data.special_awards||[]).length)+' особых наград</div><div class="profile-achievements-list">'+(featured.length?featured.map(x=>'<div class="profile-achievement '+(x.kind==='special'?'special':'')+'"><div class="ico">'+esc(x.icon||'🏆')+'</div><strong>'+esc(x.title)+'</strong><small>'+esc(x.kind==='special'?'Государственная награда':x.category||'Достижение')+'</small></div>').join(''):'<div class="summary">Гражданин пока не выставил достижения в профиль.</div>')+'</div><a href="achievements.html?id='+encodeURIComponent(id)+'">Посмотреть достижения →</a>';card.insertAdjacentElement('afterend',box)}
function tick(){css();if(location.pathname.endsWith('/profile.html')||location.pathname.endsWith('profile.html'))enhanceOwn();if(location.pathname.endsWith('/citizen.html')||location.pathname.endsWith('citizen.html'))enhancePublic()}
window.addEventListener('load',tick);const obs=new MutationObserver(tick);obs.observe(document.documentElement,{childList:true,subtree:true});setTimeout(()=>obs.disconnect(),20000);
})();