(()=>{
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let busy=false,selected=null;
 async function rpc(name,args){const {data,error}=await supabaseClient.rpc(name,args).abortSignal(AbortSignal.timeout(20000));if(error)throw Error(error.message);return data;}
 function mount(){const root=document.getElementById('founderFamilySettings');if(!root||root.dataset.ready)return;root.dataset.ready='1';
  root.innerHTML=`<div class="reward-panel"><form id="familyLookup"><label for="familyCitizenNumber">ID гражданина</label><div class="reward-controls"><input id="familyCitizenNumber" inputmode="numeric" pattern="[0-9]{1,18}" maxlength="18" required placeholder="000123"><button type="submit" class="secondary">Найти гражданина</button></div></form><p id="familySelected">Сначала выберите гражданина по ID.</p><form id="familyOverrideForm" hidden><div class="reward-controls" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr))"><label>Стаж до брака, дней<input name="marriage" type="number" min="0" max="15" step="1" required value="15"></label><label>Шаг мест для детей, дней<input name="child" type="number" min="0" max="30" step="1" required value="30"></label><label>Ожидание развода, дней<input name="divorce" type="number" min="0" max="10" step="1" required value="10"></label></div><p>0 — доступ сразу. Обычные сроки: 15 / 30 / 10 дней. Для брака условия проверяются у каждого участника: чтобы поженить двух новых граждан, задайте 0 каждому. Послабление по детям действует на общую семью: шаг 5 открывает места после 5, 10 и 15 дней брака, шаг 0 — все три сразу. Развод сокращается только для выбранного гражданина. Месяц ожидания после развода сохраняется.</p><p>Настройки действуют до отмены Основателем, в том числе в последующих браках. Даты регистрации не изменяются.</p><label>Основание изменения<input name="reason" maxlength="500" required placeholder="Например: разрешение Основателя для раннего доступа"></label><div class="reward-actions"><button type="submit" class="primary">Сохранить сроки</button><button type="button" class="secondary" id="familyReset">Вернуть обычные сроки</button></div></form><p id="familySettingsMessage" role="status"></p></div><div class="reward-panel"><h2>Выданные послабления</h2><button type="button" class="secondary" id="familyRefresh">Обновить</button><div id="familyOverrideList">Загрузка…</div></div><div class="reward-panel"><h2>История изменений</h2><p>Последние 50 изменений.</p><div id="familyOverrideHistory"></div></div>`;
  const msg=root.querySelector('#familySettingsMessage'),form=root.querySelector('#familyOverrideForm');
  function paint(d){
    if(d.selected){selected=d.selected;root.querySelector('#familySelected').textContent=selected.nickname+' · #'+selected.number.padStart(6,'0');form.hidden=false;form.elements.marriage.value=selected.marriage_days;form.elements.child.value=selected.child_days;form.elements.divorce.value=selected.divorce_days;}
    root.querySelector('#familyOverrideList').innerHTML=d.entries.map(x=>`<div style="padding:14px 0;border-bottom:1px solid #eee;overflow-wrap:anywhere"><strong>${esc(x.nickname)} · #${esc(x.number.padStart(6,'0'))}</strong><p>Брак: ${x.marriage_days} дн. · Дети: шаг ${x.child_days} дн. · Развод: ${x.divorce_days} дн.</p><p>${esc(x.reason)}</p></div>`).join('')||'<p>Персональных послаблений нет.</p>';
    root.querySelector('#familyOverrideHistory').innerHTML=d.history.map(x=>`<div style="padding:14px 0;border-bottom:1px solid #eee;overflow-wrap:anywhere"><strong>${esc(x.nickname)} · #${esc(x.number.padStart(6,'0'))}</strong><p>${esc(new Date(x.changed_at).toLocaleString('ru-RU'))} · ${esc(x.reason)}</p><p>Брак / дети / развод: ${x.previous.marriage_days} / ${x.previous.child_days} / ${x.previous.divorce_days} → ${x.replacement.marriage_days} / ${x.replacement.child_days} / ${x.replacement.divorce_days} дней.</p></div>`).join('')||'<p>Изменений пока нет.</p>';
  }
  async function run(fn){if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);msg.textContent='';try{paint(await fn());}catch(e){msg.textContent=e.message;root.querySelector('#familyOverrideList').textContent='Не удалось загрузить данные. Нажмите «Обновить».';}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  root.querySelector('#familyLookup').addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity()||busy)return;selected=null;form.hidden=true;root.querySelector('#familySelected').textContent='Проверяем гражданина…';run(()=>rpc('founder_family_settings',{p_number:root.querySelector('#familyCitizenNumber').value.trim()}));});
  async function save(reset){if(!selected||!form.reportValidity()||busy)return;const person={...selected};if(reset&&!confirm('Вернуть обычные сроки для '+person.nickname+'?'))return;
    await run(async()=>{const d=await rpc('founder_set_family_settings',{p_number:person.number,p_marriage_days:Number(form.elements.marriage.value),p_child_days:Number(form.elements.child.value),p_divorce_days:Number(form.elements.divorce.value),p_reason:form.elements.reason.value.trim(),p_reset:reset});msg.textContent='Сроки сохранены для '+person.nickname+'.';return d;});
  }
  form.addEventListener('submit',e=>{e.preventDefault();save(false);});root.querySelector('#familyReset').addEventListener('click',()=>save(true));root.querySelector('#familyRefresh').addEventListener('click',()=>run(()=>rpc('founder_family_settings',{p_number:selected?.number||null})));
  run(()=>rpc('founder_family_settings'));
 }
 const observer=new MutationObserver(()=>{mount();if(document.getElementById('founderFamilySettings')?.dataset.ready)observer.disconnect();});observer.observe(document.getElementById('adminContent'),{childList:true});mount();
})();
