(()=>{
if((location.pathname.split('/').pop()||'').toLowerCase()!=='shop.html')return;
const V2=[
{code:'cosmos_v2',emoji:'🌌',title:'Космос V2',desc:'Сложная орбитальная рамка с планетами, иллюстрированный космический фон, глубокая карточка и усиленный звёздный эффект.',price:1125},
{code:'sakura_v2',emoji:'🌸',title:'Сакура V2',desc:'Объёмные ветви и цветы сакуры вокруг аватара, рисованный садовый фон, мягкая тема и насыщенный эффект лепестков.',price:1000},
{code:'imperial_v2',emoji:'👑',title:'Имперский V2',desc:'Детализированная золотая гербовая рамка с кристаллами, дворцовый фон, богатая тёмная тема и золотые искры.',price:1500},
{code:'midnight_v2',emoji:'🖤',title:'Midnight V2',desc:'Сложная лунная рамка с острыми элементами, ночной фон, глубокая тёмная тема и кристальные осколки.',price:1125},
{code:'sky_v2',emoji:'☁️',title:'Небеса V2',desc:'Большие крылья, облака и звёздные детали вокруг аватара, воздушный небесный фон и световые частицы.',price:1000}
];
const css=document.createElement('link');css.rel='stylesheet';css.href='cosmetics-v2.css?v=4';document.head.appendChild(css);
const style=document.createElement('style');style.textContent='.premium-intro{margin:44px 0 16px}.premium-intro h2{font-size:28px;margin:0 0 8px}.premium-intro p{color:#6b6b74;line-height:1.55}.premium-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}.premium-grid .set-preview{height:168px;border-radius:15px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.22),0 9px 24px rgba(25,17,45,.16)}.premium-price-note{font-size:11px;color:#777;margin-top:-8px;margin-bottom:12px}';document.head.appendChild(style);
async function init(){let n=0;while(!window.supabase&&n++<60)await new Promise(r=>setTimeout(r,100));if(!window.supabase)return;const client=window.__neriaHeaderSb||window.supabase.createClient('https://rictvznkxkeygbrlcymn.supabase.co','sb_publishable_SVwKto14tbMtsmcDOagvCw_TVqg7he7');const {data:{session}}=await client.auth.getSession();let owned=[];if(session){const {data}=await client.rpc('my_profile_cosmetics');owned=data?.owned||[]}
const anchor=document.getElementById('cosmeticSets');if(!anchor)return;const intro=document.createElement('div');intro.className='premium-intro';intro.innerHTML='<h2>Премиальные наборы V2 <span class="v2-badge">PREMIUM</span></h2><p>V2 — это уже не просто цветовая тема. У каждого набора собственная иллюстрированная сцена профиля, большая декоративная рамка аватара, проработанная карточка и отдельный живой эффект. Стоимость — 2,5× от базовой версии.</p>';const grid=document.createElement('section');grid.className='premium-grid';grid.innerHTML=V2.map(s=>{const has=owned.includes(s.code);return '<article class="card set-card v2-card"><div class="set-preview pv-'+s.code+'"></div><div class="icon">'+s.emoji+'</div><h2>'+s.title+' <span class="v2-badge">V2</span></h2><p>'+s.desc+'</p><div class="price">'+s.price+' NR</div><div class="premium-price-note">2,5× стоимость базовой версии</div><div class="set-actions"><button class="btn" data-buy-v2="'+s.code+'" '+(has?'disabled':'')+'>'+(has?'Приобретено':'Купить')+'</button>'+(has?'<a class="btn secondary" href="cosmetics.html" style="text-decoration:none;text-align:center">Настроить</a>':'')+'</div>'+(has?'<div class="owned-label">✓ Премиальный набор в вашей коллекции</div>':'')+'</article>'}).join('');anchor.parentNode.insertBefore(intro,anchor.nextSibling);anchor.parentNode.insertBefore(grid,intro.nextSibling);
grid.addEventListener('click',async e=>{const b=e.target.closest('[data-buy-v2]');if(!b)return;const code=b.dataset.buyV2,s=V2.find(x=>x.code===code);if(!s||!confirm('Купить «'+s.title+'» за '+s.price+' NR навсегда?'))return;b.disabled=true;b.textContent='Покупка…';const {error}=await client.rpc('buy_profile_cosmetic_set',{p_code:code});if(error){alert(error.message.includes('Insufficient')?'Недостаточно NR.':error.message.includes('Already owned')?'Этот набор уже приобретён.':'Не удалось купить: '+error.message);b.disabled=false;b.textContent='Купить';return}alert('Премиальный набор добавлен в коллекцию.');location.reload()})}
init();
})();