begin;
do $$
declare u uuid[]:=array[]::uuid[]; c bigint[]:=array[]::bigint[]; nums text[]:=array[]::text[];
 uid uuid; cid bigint; num text; i integer; j jsonb; failed boolean; r uuid; mid uuid; app bigint; other_app bigint; nonce uuid; message_id text;
begin
 for i in 1..5 loop
   uid=gen_random_uuid(); insert into auth.users(id) values(uid);
   insert into public.citizens(user_id,nickname,birth_day,birth_month,created_at) values(uid,'family-chat-test-'||uid::text,1,1,now()) returning id,citizen_number::text into cid,num;
   u=array_append(u,uid);c=array_append(c,cid);nums=array_append(nums,num);
 end loop;
 insert into public.founders(user_id) values(u[1]);
 perform set_config('request.jwt.claim.sub',u[2]::text,true);
 failed=false;begin perform public.founder_family_settings(nums[2]);exception when others then failed=true;end;assert failed,'Non-founder cannot read settings';
 failed=false;begin perform public.founder_set_family_settings(nums[2],0,0,0,'unauthorized');exception when others then failed=true;end;assert failed,'Non-founder cannot grant exceptions';
 perform set_config('request.jwt.claim.sub',u[1]::text,true);
 failed=false;begin perform public.founder_set_family_settings(nums[2],16,0,0,'invalid');exception when others then failed=true;end;assert failed,'Cannot increase beyond regular limits';
 perform public.founder_set_family_settings(nums[2],0,0,0,'Test permission');
 perform set_config('request.jwt.claim.sub',u[2]::text,true);
 assert (public.family_dashboard()->>'can_marry')::boolean,'Zero grants instant eligibility';
 failed=false;begin perform public.family_action('propose',nums[3]);exception when others then failed=true;end;assert failed,'Both spouses must be eligible';
 perform set_config('request.jwt.claim.sub',u[1]::text,true);
 perform public.founder_set_family_settings(nums[3],0,30,10,'Second spouse eligibility');
 perform set_config('request.jwt.claim.sub',u[2]::text,true);
 perform public.family_action('propose',nums[3]);select id into r from neria_family.requests where proposer=c[2] and status='pending';
 perform set_config('request.jwt.claim.sub',u[3]::text,true);perform public.family_action('accept',r::text);
 j=public.family_dashboard();mid=(j->'marriage'->>'id')::uuid;
 assert (j->'marriage'->>'can_invite_child')::boolean and (j->>'child_days')::integer=0,'Child override applies to shared family';
 assert not (j->'marriage'->>'can_divorce')::boolean,'Divorce override is personal';
 failed=false;begin perform public.family_action('divorce',mid::text);exception when others then failed=true;end;assert failed,'Other spouse retains divorce wait';
 perform public.family_action('invite_child',nums[4]);select id into r from neria_family.requests where marriage_id=mid and status='pending';
 perform set_config('request.jwt.claim.sub',u[4]::text,true);perform public.family_action('accept',r::text);
 perform set_config('request.jwt.claim.sub',u[2]::text,true);perform public.family_action('accept',r::text);
 assert (select count(*) from neria_family.children where marriage_id=mid)=1,'Zero child wait but all consents required';
 assert (public.family_dashboard()->'marriage'->>'can_divorce')::boolean,'Founder granted personal instant divorce';
 perform public.family_action('divorce',mid::text);
 assert not (public.family_dashboard()->>'can_marry')::boolean,'Monthly cooldown not bypassed';
 perform set_config('request.jwt.claim.sub',u[1]::text,true);
 j=public.founder_set_family_settings(nums[2],15,30,10,'Restore defaults',true);
 assert j->'selected'->>'marriage_days'='15' and j->'selected'->>'child_days'='30' and j->'selected'->>'divorce_days'='10','Reset defaults';
 assert (select count(*) from neria_family.wait_audit where citizen_id=c[2])=2,'Audit retains grant and reset';
 -- Application-scoped conversations.
 insert into public.government_role_applications(user_id,citizen_id,requested_role,statement,status) values(u[4],c[4],'journalist','Test statement','pending') returning id into app;
 insert into public.government_role_applications(user_id,citizen_id,requested_role,statement,status) values(u[5],c[5],'mvd','Other private statement','pending') returning id into other_app;
 nonce=gen_random_uuid();j=public.send_role_application_message(app,'Founder question',nonce);message_id=j->>'id';
 assert public.send_role_application_message(app,'Founder question',nonce)->>'id'=message_id,'Idempotent retries';
 assert (select count(*) from neria_government.application_messages where application_id=app)=1,'Only one message';
 perform set_config('request.jwt.claim.sub',u[4]::text,true);
 j=public.role_application_chat(app);assert jsonb_array_length(j->'messages')=1 and j->'messages'->0->>'body'='Founder question','Applicant sees founder question';
 assert j->'messages'->0->>'mine'='false','Sender attribution';
 perform public.send_role_application_message(app,'Applicant answer',gen_random_uuid());
 failed=false;begin perform public.role_application_chat(other_app);exception when others then failed=true;end;assert failed,'Cannot read someone else application';
 failed=false;begin perform public.send_role_application_message(other_app,'Intrusion',gen_random_uuid());exception when others then failed=true;end;assert failed,'Cannot write someone else application';
 perform set_config('request.jwt.claim.sub',u[5]::text,true);
 failed=false;begin perform public.role_application_chat(app);exception when others then failed=true;end;assert failed,'Outsider privacy';
 perform set_config('request.jwt.claim.sub',u[1]::text,true);
 j=public.role_application_chat(app);assert jsonb_array_length(j->'messages')=2,'Founder sees both sides';
 update public.government_role_applications set status='accepted' where id=app;
 assert public.role_application_chat(app)->>'status'='accepted','History survives decision';
 -- Pagination retains access to older messages.
 insert into neria_government.application_messages(application_id,sender_id,founder_message,body,nonce) select app,u[1],true,'Older message '||s,gen_random_uuid() from generate_series(1,101) s;
 j=public.role_application_chat(app);assert jsonb_array_length(j->'messages')=100 and (j->>'has_more')::boolean,'Chat pagination';
 j=public.role_application_chat(app,(j->>'oldest')::bigint);assert jsonb_array_length(j->'messages')=3,'Older page available';
 perform set_config('request.jwt.claim.sub',u[4]::text,true);
 update public.citizens set citizenship_status='banned' where id=c[4];
 failed=false;begin perform public.role_application_chat(app);exception when others then failed=true;end;assert failed,'Banned applicant denied';
 assert not has_table_privilege('authenticated','neria_government.application_messages','SELECT'),'No direct message reads';
 assert not has_table_privilege('authenticated','neria_family.wait_overrides','UPDATE'),'No direct override writes';
 assert not has_function_privilege('anon','public.role_application_chat(bigint,bigint)','EXECUTE'),'No anonymous chat';
 assert not has_function_privilege('anon','public.founder_family_settings(text)','EXECUTE'),'No anonymous founder settings';
end;
$$;
rollback;
